### ISSUE TITLE
Any Examples that Utilize Encryption?

### ISSUE THREAD

**Issue by jimjeffers** [readium/SDKLauncher-iOS#56]
Hey guys,

I'm trying to find any examples with Readium that launch encrypted epub files. Is there a specific process for encrypting epubs to work with Readium? And are there any specific settings that need to be specified in the SDK to decrypt said epubs?

**Comment by john-nowak** [comment]
I don't think you'll be able to find any examples. Your typical encrypted EPUB uses Adobe's DRM, and there is no open implementation anyone could share with you. You'll likely have to secure your own trial version of RMSDK via a vendor such as Datalogics or Webqem to make any progress.

**Comment by rkwright** [comment]
To add a little background, Readium per se does not out of the box support any DRM and will not.  DRM by its very nature is propietary and we are open source and deliberately DRM-agnostic.  It is up to our SDK partners to implement whatever DRM support they want, whether it be "Adobe" (Classic or PassHash), Sony Marlin, SCP (née LCP) etc. 

What might be interesting and useful would be to have some trivial, non-proprietary DRM implementation, e.g. something like Caesar's shift (where each character is shifted character, etc. A modern equivalent would be to roll all 8 bits one bit left, for example)

We would love to have someone implement this feature.  Volunteers?

**Comment by danielweck** [comment]
Regarding Ric's "call for participation" above ;) I would suggest taking a look at this (slightly out of date) wiki page which describes how a 'content filter' can be added in the ReadiumSDK processing 'chain' in order to decrypt files on the fly (via the built-in HTTP server), and how support for streaming media assets can be implemented (HTTP byte range protocol):
https://github.com/readium/readium-sdk/wiki/ContentFilterEncryptedMedia
It's not an exacting blueprint, but a pretty decent starting point anyway.

**Comment by jimjeffers** [comment]
@rkwright @danielweck I'm not sure my client will fund that endeavor :) 

Their reader supports PDF and epubs. We currently encrypt the PDF files with RNCryptor and PSPDFKit has a CryptoDataSource object that can decrypt parts of the PDF file on the fly. This works incredibly well. I don't know if we could build something similar. It sounds like the 'content filter' solution is similar to what we're doing with PSPDFKit. I'll check it out!

Thanks guys!
