### ISSUE TITLE
Using in swift

### ISSUE THREAD

**Issue by SashaKrug** [readium/SDKLauncher-iOS#75]
Thanks for good work)
I first time using Readium, i hope you can explain me, how using this lib in swift.

**Comment by danielweck** [comment]
There's a short discussion on Slack about Swift:
https://readium.slack.com/archives/sdk/p1456480313000003

If you need to join Slack:
http://readium-slack.herokuapp.com

Basically, the likelyhood of finding guidance about Readium-Swift integration at this stage is very low, because no contribution has been available in the open source / public domain, so far.

You will probably need bridging headers, but that's as much as I can help you.

 I am closing this issue as there are no plans to implement Swift in the basic iOS launcher app. Please, you may continue the discussion on Slack.
